version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.7.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn clean package
  test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: |
          echo "Running tests..."
          mvn test
  scan:
    docker:
        - image: cimg/openjdk:17.0.7
    environment:
        IMAGE_NAME: privateoc/education-space
    steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - run: docker build -t $IMAGE_NAME .
        - snyk/scan:
            severity-threshold: critical
            docker-image-name: $IMAGE_NAME
  build-and-push:
    executor: docker/docker
    docker:
      - image: cimg/openjdk:17.0.7
        auth:
            username: $DOCKER_LOGIN
            password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: privateoc/education-space
          tag: ${CIRCLE_SHA1}
      - docker/push:
          image: privateoc/education-space
          tag: ${CIRCLE_SHA1}
  deploy:
    docker:
        - image: cimg/node:16.10
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku container:push web -a neowc-su-devops
                heroku container:release web -a neowc-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
      - build-and-push:
          requires:
            - test
            - scan
      - deploy:
          requires:
            - build-and-push